using Microsoft.EntityFrameworkCore.Migrations;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Database.Migrations
{
    /// <inheritdoc />
    public partial class twe : Migration
    {
        /// <inheritdoc />
        protected override void Up(MigrationBuilder migrationBuilder)
        {
         
            migrationBuilder.Sql(@"
        ALTER TABLE ""OrderDetails"" ALTER COLUMN ""OrderDetailsId"" DROP IDENTITY IF EXISTS;
        ALTER TABLE ""OrderDetails"" ALTER COLUMN ""OrderDetailsId"" TYPE integer USING ""OrderDetailsId""::integer;
        ALTER TABLE ""OrderDetails"" ALTER COLUMN ""OrderDetailsId"" ADD GENERATED BY DEFAULT AS IDENTITY;
    ");
        }

        protected override void Down(MigrationBuilder migrationBuilder)
        {
            migrationBuilder.Sql(@"
        ALTER TABLE ""OrderDetails"" ALTER COLUMN ""OrderDetailsId"" DROP IDENTITY IF EXISTS;
        ALTER TABLE ""OrderDetails"" ALTER COLUMN ""OrderDetailsId"" TYPE text;
    ");
        }

       
    }
}
